export const CHANGE_WORKSHEET_SIDEBAR = 'CHANGE_WORKSHEET_SIDEBAR';

export const SHOW_HIDE_NAV_PROFILE_MENU = 'SHOW_HIDE_NAV_PROFILE_MENU';
export const NAV_LEFT_MENU_LIMIT = 'NAV_LEFT_MENU_LIMIT';

export const GET_FORM_DATA = 'GET_FORM_DATA';
export const RESET_FORM_DATA = 'RESET_FORM_DATA';
export const SUITE_INFORMATION_FORM_DATA = 'SUITE_INFORMATION_FORM_DATA';
